codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

    patch:
      default:
        target: 90%
        threshold: 0%
        base: auto
        if_not_found: success
        if_ci_failed: error
        only_pulls: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/__pycache__/**/*"
  - "**/test_*.py"
  - "**/*_test.py"
  - "setup.py"
  - "docs/**/*"