name: Coverage Minimal

on:
  push:
    branches: [feat/eng-114-fix-timeout-issue-v2]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install and test
      run: |
        pip install -e .[test]
        pytest --cov=src --cov-report=term

    - name: Show coverage
      run: echo "Coverage test completed"